version: '3.3'
services:
  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - '6379:6379'
  monitor: 
    restart: on-failure
    build:
      context: .
      dockerfile: ./monitor.Dockerfile
  
  runner:
    restart: on-failure
    build:
      context: .
      dockerfile: ./runner.Dockerfile
    depends_on:
      - monitor